baseURL = "http://debatelibrary.netlify.app"
languageCode = "en-us"
title = "Debate Library"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = 'authors'


[menu]
[[menu.main]]
    name = 'Tournaments'
    pageRef = '/categories/tournaments'
    pre = 'bi-trophy'
    weight = 10
[[menu.main]]
    name = 'Workshops'
    pageRef = '/categories/workshops'
    pre = 'bi-easel'
    weight = 20
[[menu.main]]
    name = 'Tags'
    pageRef = '/tags'
    pre = 'bi-tags'
    weight = 30
[[menu.main]]
    name = 'Authors'
    pageRef = '/authors'
    pre = 'bi-person'
    weight = 40